// <auto-generated />
using System;
using GrowthTrigal.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrowthTrigal.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191011143941_CompleteDB")]
    partial class CompleteDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrowthTrigal.Web.Data.Entities.Flower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("VarietyName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Flowers");
                });

            modelBuilder.Entity("GrowthTrigal.Web.Data.Entities.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BedName")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<int>("BlockNumber")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("GrowthTrigal.Web.Data.Entities.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FlowerId");

                    b.Property<DateTime>("MeasurementDate");

                    b.Property<float>("Mesaurement")
                        .HasMaxLength(5);

                    b.Property<int?>("UPId");

                    b.HasKey("Id");

                    b.HasIndex("FlowerId");

                    b.HasIndex("UPId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("GrowthTrigal.Web.Data.Entities.UP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AliasFarm")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<int>("FarmName")
                        .HasMaxLength(25);

                    b.Property<int?>("FlowerId");

                    b.Property<int?>("HomeId");

                    b.HasKey("Id");

                    b.HasIndex("FlowerId");

                    b.HasIndex("HomeId");

                    b.ToTable("UPs");
                });

            modelBuilder.Entity("GrowthTrigal.Web.Data.Entities.Measurement", b =>
                {
                    b.HasOne("GrowthTrigal.Web.Data.Entities.Flower", "Flower")
                        .WithMany("Measurements")
                        .HasForeignKey("FlowerId");

                    b.HasOne("GrowthTrigal.Web.Data.Entities.UP", "UP")
                        .WithMany("Measurements")
                        .HasForeignKey("UPId");
                });

            modelBuilder.Entity("GrowthTrigal.Web.Data.Entities.UP", b =>
                {
                    b.HasOne("GrowthTrigal.Web.Data.Entities.Flower", "Flower")
                        .WithMany("UPs")
                        .HasForeignKey("FlowerId");

                    b.HasOne("GrowthTrigal.Web.Data.Entities.Home", "Home")
                        .WithMany("UPs")
                        .HasForeignKey("HomeId");
                });
#pragma warning restore 612, 618
        }
    }
}
